#!/bin/bash
#
# Gera src/fontIds.h.
#
# O ID de uma fonte e a soma dos SHA-256 dos cabecalhos que a compoem, dobrada
# em 32 bits com sinal. Isso significa que o ID MUDA quando a fonte muda, que e
# o ponto: um cache de layout gravado com a fonte antiga nao casa com a nova, e
# o leitor reprocessa em vez de desenhar com metricas erradas.
#
# Antes este arquivo tinha um bloco ruby copiado para cada tamanho. Virou laco
# quando a lista de tamanhos passou de quatro para seis e a copia ficou maior
# que a logica.
#
#   bash build-font-ids.sh > ../../../src/fontIds.h

set -e
cd "$(dirname "$0")/../builtinFonts"

READER_SIZES=(14 16 18 20)
UI_SIZES=(10 12 14 16)

# Soma os hashes dos arquivos dados e imprime o ID.
font_id() {
  ruby -rdigest -e 'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' "$@"
}

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

FONT_ID_NAMES=()

for family in notoserif notosans; do
  upper=$(echo "$family" | tr '[:lower:]' '[:upper:]')
  for size in "${READER_SIZES[@]}"; do
    name="${upper}_${size}_FONT_ID"
    echo "#define ${name} ($(font_id "./${family}_${size}_regular.h" "./${family}_${size}_bold.h" \
      "./${family}_${size}_bolditalic.h" "./${family}_${size}_italic.h"))"
    FONT_ID_NAMES+=("$name")
  done
done

for size in "${UI_SIZES[@]}"; do
  name="UI_${size}_FONT_ID"
  echo "#define ${name} ($(font_id "./ubuntu_${size}_regular.h" "./ubuntu_${size}_bold.h"))"
  FONT_ID_NAMES+=("$name")
done

echo "#define SMALL_FONT_ID ($(font_id "./notosans_8_regular.h"))"
FONT_ID_NAMES+=(SMALL_FONT_ID)

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for name in "${FONT_ID_NAMES[@]}"; do
  echo "static_assert(${name} != 0, \"Font ID collision with sentinel\");"
done
