#!/bin/bash
#
# Generates src/fontIds.h.
#
# A font's ID is the sum of the SHA-256 of the headers that make it up, folded
# into a signed 32-bit value. That means the ID CHANGES when the font changes,
# which is the point: a layout cache written with the old font does not match
# the new one, and the reader reprocesses instead of drawing with wrong
# metrics.
#
# This file used to carry a ruby block copied per size. It became a loop when
# the size list went from four to six and the copy grew larger than the logic.
#
#   bash build-font-ids.sh > ../../../src/fontIds.h

set -e
cd "$(dirname "$0")/../builtinFonts"

READER_SIZES=(14 16 18 20)
UI_SIZES=(10 12 14 16 20 24)

# Sums the given files' hashes and prints the ID.
font_id() {
  ruby -rdigest -e 'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' "$@"
}

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

FONT_ID_NAMES=()

for family in notoserif notosans; do
  upper=$(echo "$family" | tr '[:lower:]' '[:upper:]')
  for size in "${READER_SIZES[@]}"; do
    name="${upper}_${size}_FONT_ID"
    echo "#define ${name} ($(font_id "./${family}_${size}_regular.h" "./${family}_${size}_bold.h" \
      "./${family}_${size}_bolditalic.h" "./${family}_${size}_italic.h"))"
    FONT_ID_NAMES+=("$name")
  done
done

for size in "${UI_SIZES[@]}"; do
  name="UI_${size}_FONT_ID"
  echo "#define ${name} ($(font_id "./ubuntu_${size}_regular.h" "./ubuntu_${size}_bold.h"))"
  FONT_ID_NAMES+=("$name")
done

echo "#define SMALL_FONT_ID ($(font_id "./notosans_8_regular.h"))"
FONT_ID_NAMES+=(SMALL_FONT_ID)

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for name in "${FONT_ID_NAMES[@]}"; do
  echo "static_assert(${name} != 0, \"Font ID collision with sentinel\");"
done
