#pragma once
#include "I18nKeys.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.
// clang-format off

namespace i18n_strings {

extern const char STRINGS_EN_DATA[];
extern const uint16_t OFFSETS_EN[];
extern const char STRINGS_AR_DATA[];
extern const uint16_t OFFSETS_AR[];
extern const char STRINGS_BE_DATA[];
extern const uint16_t OFFSETS_BE[];
extern const char STRINGS_BG_DATA[];
extern const uint16_t OFFSETS_BG[];
extern const char STRINGS_BS_DATA[];
extern const uint16_t OFFSETS_BS[];
extern const char STRINGS_CA_DATA[];
extern const uint16_t OFFSETS_CA[];
extern const char STRINGS_CAV_DATA[];
extern const uint16_t OFFSETS_CAV[];
extern const char STRINGS_CS_DATA[];
extern const uint16_t OFFSETS_CS[];
extern const char STRINGS_DA_DATA[];
extern const uint16_t OFFSETS_DA[];
extern const char STRINGS_DE_DATA[];
extern const uint16_t OFFSETS_DE[];
extern const char STRINGS_ES_DATA[];
extern const uint16_t OFFSETS_ES[];
extern const char STRINGS_FA_DATA[];
extern const uint16_t OFFSETS_FA[];
extern const char STRINGS_FI_DATA[];
extern const uint16_t OFFSETS_FI[];
extern const char STRINGS_FR_DATA[];
extern const uint16_t OFFSETS_FR[];
extern const char STRINGS_HE_DATA[];
extern const uint16_t OFFSETS_HE[];
extern const char STRINGS_HU_DATA[];
extern const uint16_t OFFSETS_HU[];
extern const char STRINGS_ID_DATA[];
extern const uint16_t OFFSETS_ID[];
extern const char STRINGS_IT_DATA[];
extern const uint16_t OFFSETS_IT[];
extern const char STRINGS_KK_DATA[];
extern const uint16_t OFFSETS_KK[];
extern const char STRINGS_LT_DATA[];
extern const uint16_t OFFSETS_LT[];
extern const char STRINGS_NB_DATA[];
extern const uint16_t OFFSETS_NB[];
extern const char STRINGS_NL_DATA[];
extern const uint16_t OFFSETS_NL[];
extern const char STRINGS_OOK_DATA[];
extern const uint16_t OFFSETS_OOK[];
extern const char STRINGS_PL_DATA[];
extern const uint16_t OFFSETS_PL[];
extern const char STRINGS_PT_DATA[];
extern const uint16_t OFFSETS_PT[];
extern const char STRINGS_P2_DATA[];
extern const uint16_t OFFSETS_P2[];
extern const char STRINGS_RO_DATA[];
extern const uint16_t OFFSETS_RO[];
extern const char STRINGS_RU_DATA[];
extern const uint16_t OFFSETS_RU[];
extern const char STRINGS_SK_DATA[];
extern const uint16_t OFFSETS_SK[];
extern const char STRINGS_SI_DATA[];
extern const uint16_t OFFSETS_SI[];
extern const char STRINGS_SV_DATA[];
extern const uint16_t OFFSETS_SV[];
extern const char STRINGS_TR_DATA[];
extern const uint16_t OFFSETS_TR[];
extern const char STRINGS_UK_DATA[];
extern const uint16_t OFFSETS_UK[];
extern const char STRINGS_VI_DATA[];
extern const uint16_t OFFSETS_VI[];

}  // namespace i18n_strings
