#pragma once

#include <builtinFonts/notoserif_14_bold.h>
#include <builtinFonts/notoserif_14_bolditalic.h>
#include <builtinFonts/notoserif_14_italic.h>
#include <builtinFonts/notoserif_14_regular.h>
#include <builtinFonts/notoserif_16_bold.h>
#include <builtinFonts/notoserif_16_bolditalic.h>
#include <builtinFonts/notoserif_16_italic.h>
#include <builtinFonts/notoserif_16_regular.h>
#include <builtinFonts/notoserif_18_bold.h>
#include <builtinFonts/notoserif_18_bolditalic.h>
#include <builtinFonts/notoserif_18_italic.h>
#include <builtinFonts/notoserif_18_regular.h>
#include <builtinFonts/notoserif_20_bold.h>
#include <builtinFonts/notoserif_20_bolditalic.h>
#include <builtinFonts/notoserif_20_italic.h>
#include <builtinFonts/notoserif_20_regular.h>
#include <builtinFonts/notoserif_22_bold.h>
#include <builtinFonts/notoserif_22_bolditalic.h>
#include <builtinFonts/notoserif_22_italic.h>
#include <builtinFonts/notoserif_22_regular.h>
#include <builtinFonts/notoserif_24_bold.h>
#include <builtinFonts/notoserif_24_bolditalic.h>
#include <builtinFonts/notoserif_24_italic.h>
#include <builtinFonts/notoserif_24_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/notosans_20_bold.h>
#include <builtinFonts/notosans_20_bolditalic.h>
#include <builtinFonts/notosans_20_italic.h>
#include <builtinFonts/notosans_20_regular.h>
#include <builtinFonts/notosans_22_bold.h>
#include <builtinFonts/notosans_22_bolditalic.h>
#include <builtinFonts/notosans_22_italic.h>
#include <builtinFonts/notosans_22_regular.h>
#include <builtinFonts/notosans_24_bold.h>
#include <builtinFonts/notosans_24_bolditalic.h>
#include <builtinFonts/notosans_24_italic.h>
#include <builtinFonts/notosans_24_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
#include <builtinFonts/ubuntu_14_bold.h>
#include <builtinFonts/ubuntu_14_regular.h>
#include <builtinFonts/ubuntu_16_bold.h>
#include <builtinFonts/ubuntu_16_regular.h>
