// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_14_FONT_ID (-928381217)
#define NOTOSERIF_16_FONT_ID (17214534)
#define NOTOSERIF_18_FONT_ID (840051567)
#define NOTOSERIF_20_FONT_ID (-1759219852)
#define NOTOSERIF_22_FONT_ID (1584040457)
#define NOTOSERIF_24_FONT_ID (-1648593767)
#define NOTOSANS_14_FONT_ID (-1413326613)
#define NOTOSANS_16_FONT_ID (116566294)
#define NOTOSANS_18_FONT_ID (-348426591)
#define NOTOSANS_20_FONT_ID (1274733257)
#define NOTOSANS_22_FONT_ID (-1555155226)
#define NOTOSANS_24_FONT_ID (1752581789)
#define UI_10_FONT_ID (1322569422)
#define UI_12_FONT_ID (1831230762)
#define UI_14_FONT_ID (-583199504)
#define SMALL_FONT_ID (1465627787)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_22_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_24_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_22_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_24_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
