// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_14_FONT_ID (951361991)
#define NOTOSERIF_16_FONT_ID (1484499681)
#define NOTOSERIF_18_FONT_ID (1222239992)
#define NOTOSERIF_20_FONT_ID (1259953572)
#define NOTOSANS_14_FONT_ID (-1078045977)
#define NOTOSANS_16_FONT_ID (-224767943)
#define NOTOSANS_18_FONT_ID (1674469527)
#define NOTOSANS_20_FONT_ID (-1893669446)
#define UI_10_FONT_ID (1312641442)
#define UI_12_FONT_ID (1208726697)
#define UI_14_FONT_ID (-872550046)
#define UI_16_FONT_ID (1335798897)
#define UI_20_FONT_ID (1017928755)
#define UI_24_FONT_ID (1953731187)
#define SMALL_FONT_ID (-1040861745)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_24_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
