// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define NOTOSERIF_14_FONT_ID (-892147015)
#define NOTOSERIF_16_FONT_ID (169981735)
#define NOTOSERIF_18_FONT_ID (-24202191)
#define NOTOSERIF_20_FONT_ID (-2074348489)
#define NOTOSANS_14_FONT_ID (-1018067731)
#define NOTOSANS_16_FONT_ID (-279676897)
#define NOTOSANS_18_FONT_ID (-1880903303)
#define NOTOSANS_20_FONT_ID (1146470037)
#define UI_10_FONT_ID (-1017132632)
#define UI_12_FONT_ID (-1396802104)
#define UI_14_FONT_ID (-1020948769)
#define UI_16_FONT_ID (-781622806)
#define SMALL_FONT_ID (-1633109161)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(NOTOSERIF_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSERIF_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_20_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
